overblog_graphql:
  definitions:
    schema:
      query: RootQuery
    mappings:
      types:
        - type: graphql
          dir: "%kernel.project_dir%/config/graphql/types"
          suffix: null
