Author:
  type: object
  config:
    fields:
      id:
        type: ID!
      name:
        type: String!
      numberBooks:
        type: Int!

AuthorData:
  type: input-object
  config:
    fields:
      name:
        type: String!
        validation:
          - NotBlank: ~
          - Length:
              min: 2
              max: 128
              normalizer: trim

AuthorFilters:
  type: input-object
  config:
    fields:
      name:
        type: String
      page:
        type: Int
        validation:
          - GreaterThanOrEqual: 1
      limit:
        type: Int
        validation:
          - GreaterThanOrEqual: 5
          - LessThanOrEqual: 200