Book:
  type: object
  config:
    fields:
      id:
        type: ID!
      name:
        type: String!
      description:
        type: String
      publicationDate:
        type: String
      authors:
        type: '[Author!]!'

BookData:
  type: input-object
  config:
    fields:
      name:
        type: String!
        validation:
          - Length:
              min: 2
              max: 256
              normalizer: trim
      description:
        type: String!
        validation:
          - Length:
              max: 1024
              normalizer: trim
      publicationDate:
        type: String
        validation:
          - App\Constraints\PublicationDateConstraint: ~
      authors:
        type: '[ID!]!'
        validation:
          - NotBlank: ~
          - All:
              constraints:
                 - App\Constraints\AuthorIdConstraint: ~

BooksFilters:
  type: input-object
  config:
    validation:
      - App\Constraints\BooksSearchingFilterConstraint: ~
    fields:
      name:
        type: String
        validation:
          - Length:
              max: 256
      description:
        type: String
        validation:
          - Length:
              max: 1024
      minPublicationDate:
        type: String
        validation:
          - Date: ~
      maxPublicationDate:
        type: String
        validation:
          - Date: ~
      page:
        type: Int
        validation:
          - GreaterThanOrEqual: 1
      limit:
        type: Int
        validation:
          - GreaterThanOrEqual: 5
          - LessThanOrEqual: 200

