Book:
  type: object
  config:
    fields:
      id:
        type: ID!
      name:
        type: String!
      description:
        type: String
      publicationDate:
        type: String
      authors:
        type: '[Author!]!'

BookData:
  type: input-object
  config:
    fields:
      name: String!
      description: String
      publicationDate: String
      authors: '[ID!]!'

BooksFilters:
  type: input-object
  config:
    fields:
      name: String
      description: String
      minPublicationDate: String
      maxPublicationDate: String
      page: Int
      limit: Int
